Report failing tests to the PR

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -15,5 +15,23 @@ jobs:
         with:
           version: v1.0.20-alpha
 
-      - run: aiken check
+      - run: |
+          set -o pipefail
+          aiken check | tee aiken.log
+          RESULT=$?
+          if [ $RESULT -neq 0 ]; then
+            FAILING_TESTS=$(grep "FAIL" aiken.log -A 1)
+            echo "FAILING_TESTS=$FAILING_TESTS" >> $GITHUB_ENV
+            exit $RESULT
+          fi
       - run: aiken build
+      - uses: actions/github-script@v6
+        if: ${{ env.FAILING_TESTS }}
+        with:
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: `Tests failed:\n\n\`\`\`${{ env.FAILING_TESTS }}`
+            })
